### PR TITLE
GSW-1838 fix: test errors are fixed

### PR DESCRIPTION
**Pull request by onlyhyde**
- Integrate helper functions for tests
- Change file extensions to prevent test code in the test folder from being executed
- Fixing failure errors due to code integration
- Known issue : Fixed additional test failure case related to getter

### CODE REVIEW

**Comment by onlyhyde** [comment]
@r3v4s 
There are still test failures related to the getter. There are a lot of functions that need to be fixed, so I'll ask the existing person in charge. Also, the pool_manager related test code is all outdated. Please fix it according to our rule.

**Comment by onlyhyde** [comment]
With the additional commit from @r3v4s , all test code will pass when the current PR is applied.

**Review by notJoon — APPROVED** [review]

**Review by r3v4s — APPROVED** [review]
LGTM 👍 

Just simple question,
Can we make `users.Resolve(admin)` it as var or const ??
I really don't see pros for keep resolving AddressOrName type to address.

**Comment by r3v4s** [comment]
FYI, @onlyhyde @notJoon 

to finish #414 (which also includes work from #412 #413) this pr needs to be merge first, so I can update some test cases without many conflicts.

**Pull request merged**
